Flas 22 page error 404
Kicka3/flashCards pull request #37
Opened 2024-04-21 09:47 UTC by Vaone

Dear Kirill,

i`ve done this page, please approve or comment pull request

2024-04-21 16:15 UTC, Kicka3 commented
Добавь 404 в сторибук плез

2024-04-21 16:16 UTC, Kicka3 requested changes
add storybook

2024-04-21 18:59 UTC, Vaone commented
done

2024-04-22 13:32 UTC, Kicka3 approved these changes

2024-04-22 13:32 UTC, merged